## 协程泄漏

协程泄漏不可管控问题在go程序员编写代码的时候太常见了，我刚刚进去公司看代码，就发现所有的协程创建基本上都是直接  `go func(){}()`  ,完全没有对协程进行控制。结果有一次内存爆了，协程占内存十几个G，导致OOM。大概的代码如下所示。

```go
func main() {
	go someFunc()
	select {}
}
func someFunc() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("recover err: ", err)
			go someFunc()
		}
	}()
	go aFunc()
	go bFunc()

	if someFunc2() {
		panic("someFunc2 err")
	}
	//一些业务逻辑
	time.Sleep(time.Second)
}
func aFunc() {
	//一直在监听某事件a
	select {}
}
func bFunc() {
	//一直在监听某事件b
	select {}
}

func someFunc2() bool {
	//由于某些原因一直返回true
	return true
}

```

就这样一直  `panic`  一直  `recover`  ，直到OOM。还好是在测试环境中发现的，生产环境暂未出现，这下好了，大家开始改代码，对所有的协程加  `context`  或者返回一个  `chan`  进行控制，但是工作量太大了，所有的调用方都得改，所以只能先把出问题的某条调用线路改了，以后再有时间慢慢改。

还有一个问题，是返回  `stop chan`  的时候要注意的，也是我发现的一个bug，大概代码如下：

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	stop := someFunc()
	time.Sleep(10 * time.Second)
	stop <- struct{}{}
	select {}
}
func someFunc() chan struct{} {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("recover err：", err)
			someFunc()
		}
	}()
	stop := make(chan struct{})
	//业务逻辑
	time.Sleep(time.Second)

	if !someFunc1() {
		panic("someFunc1 panic")
	}
	//协程
	go func() {
		for {
			select {
			case <-stop:
				return
			default:
				time.Sleep(time.Second)
				fmt.Println("hello world")
			}
		}
	}()
	return stop
}
func someFunc1() bool {
	//返回true or false
	//return true
	return false
}

```

如果  `someFunc1`  第一次返回的是  `false`  ，那么这个stop chan将不能控制  `someFunc`  函数中创建的匿名协程的退出。

协程泄漏还有一个超级大的问题，也是我遇到过的，那就是泄漏的协程收到某些信号可能造成全局变量的改变，我遇到的就是全局的某个tcp连接被某个泄漏的协程关闭了。导致当我跑单测的时候，出现百分之七十跑通，百分之三十跑不通的情况，这种情况对在线业务的危害极大。